title: Jake's Space
theme: minima
author: Jake Blue
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Jake's practise blog.

# social links
twitter_username: jakebluereal # DO NOT include the @ character, or else the build will fail!
github_username:  jakeblue99 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
